name: profile
description: Profile feature package containing user profile management functionality
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.4"

dependencies:
  app_core:
    path: ../../app_core
  async: 2.13.0
  auto_route: 7.8.4
  domain:
    path: ../../domain
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.2
  image_picker: ^1.1.2
  injectable: 2.5.0
  resources:
    path: ../../resources
  rxdart: 0.28.0
  shared:
    path: ../../shared

dev_dependencies:
  auto_route_generator: 7.3.2
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.6.2
  logging: ^1.3.0
  mocktail: ^1.0.4