name: resources
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  intl: 0.20.2
  intl_utils: 2.8.10

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n
