name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.4"

dependencies:
  async: 2.13.0
  dartx: 1.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  injectable: 2.5.0
  # meta: 1.16.0
  resources:
    path: ../resources
  rxdart: 0.28.0
  shared:
    path: ../shared
  tuple: 2.0.2

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  injectable_generator: ^2.7.0
  logging: ^1.3.0
  mocktail: ^1.0.4
  nals_lints:
    path: ../nals_lints
