name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  app_core:
    path: ../app_core
  async: 2.13.0
  authentication:
    path: ../features/authentication
  auto_route: 7.8.4
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartx: 1.2.0
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: 18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get_it: ^8.0.2
  home:
    path: ../features/home
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  initializer:
    path: ../initializer
  injectable: 2.5.0
  product:
    path: ../features/product
  profile:
    path: ../features/profile
  resources:
    path: ../resources
  rxdart: 0.28.0
  shared:
    path: ../shared
  tuple: 2.0.2
dev_dependencies:
  auto_route_generator: 7.3.2
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.9.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.6.2
  logging: ^1.3.0
  mocktail: ^1.0.4
  nals_lints:
    path: ../nals_lints

# Config generate when build
flutter_gen:
  output: lib/resource/generated
  line_length: 160

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/
