name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.4"

dependencies:
  android_id: ^0.4.0
  async: ^2.13.0
  dartx: 1.2.0
  decimal: ^3.2.1
  device_info_plus: ^11.3.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_udid: ^4.0.0
  injectable: 2.5.0
  intl: ^0.20.2
  mime: ^2.0.0
  package_info_plus: ^8.1.0
  path_provider: ^2.1.5
  rxdart: 0.28.0
  timezone: ^0.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.7.0
  logging: ^1.3.0
  mocktail: ^1.0.4
  nals_lints:
    path: ../nals_lints
